
SEQUENCE_LENGTH = 10
BATCH_SIZE = 32
TRAIN_SPLIT = 0.8
VAL_SPLIT = 0.2
EPOCHS = 1
LEARNING_RATE = 2e-5
PRE_TRAINED_MODEL_NAME = "distil_bert_base_en_uncased"
PREPROCESSOR_NAME = "distil_bert_base_en"
NUM_CLASSES = 11
SAMPLE_FRAC = 0.01
