
SEQUENCE_LENGTH = 256
BATCH_SIZE = 32
TRAIN_SPLIT = 0.7
VAL_SPLIT = 0.4
EPOCHS = 2
LEARNING_RATE = 2e-5
PRE_TRAINED_MODEL_NAME = "distil_bert_base_en_uncased"
PREPROCESSOR_NAME = "distil_bert_base_en"
NUM_CLASSES = 11
SAMPLE_FRAC = 0.1
DROPOUT_RATE = 0.2
