
SEQUENCE_LENGTH = 10
BATCH_SIZE = 32
TRAIN_SPLIT = 0.8
VAL_SPLIT = 0.2
EPOCHS = 1
LEARNING_RATE = 2e-5
PRE_TRAINED_MODEL_NAME = 'bert-base-uncased'
PREPROCESSOR_NAME = "bert-base-en"
NUM_CLASSES = 11
